version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app.env.db
    ports:
      - "55433:5432"
    networks:
      - healthy-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8088:8088"
    networks:
      - healthy-network
    depends_on:
      - postgres
    entrypoint: 
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]

networks:
  healthy-network:

volumes:
  postgres_data: