ALTER TABLE body_records ALTER COLUMN id DROP DEFAULT;
ALTER TABLE meals ALTER COLUMN id DROP DEFAULT;
ALTER TABLE exercises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE diaries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE blog_posts ALTER COLUMN id DROP DEFAULT;